# Generated by Django 5.2.4 on 2025-07-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_app', '0003_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
    ]
